# Generated by Django 4.1.2 on 2022-11-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('subject', models.TextField()),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qry_title', models.CharField(max_length=200)),
                ('qry_cate', models.CharField(max_length=100)),
                ('myfiles', models.FileField(upload_to='myNotes')),
                ('comments', models.TextField()),
                ('submitted_user', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
