# Generated by Django 4.1.2 on 2022-11-14 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usersignup_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 21, 29, 52, 172300)),
        ),
    ]
